/*
 Publisher
 Released under the [Apache License 2.0](http://www.apache.org/licenses/LICENSE-2.0.html).
 Made by Jeff Pickhardt <{{ my last name }}@gmail.com>
*/
(function(){var c,e=function(b,a){return function(){return b.apply(a,arguments)}},f=Array.prototype.slice;typeof window!=="undefined"?(c=window,c.exports=c):c=global;exports.Publisher=function(){function b(a,g){var d;if(this instanceof b){if(g==null)throw"Publisher must NOT be called with the new keyword.";this.name=a;this.value=void 0;this.afterChangeSubscribers=[];this.beforeChangeSubscribers=[];this.onGetSubscribers=[];this.afterSetSubscribers=[];this.beforeSetSubscribers=[];return this}else{if(this._publisherStash==
null)this._publisherStash={};this._publisherStash[a]=new b(a,!0);typeof(d=this.Object).defineProperty=="function"&&d.defineProperty(this,a,{get:e(function(){return this._publisherStash[a].get()},this),set:e(function(b){return this._publisherStash[a].set(b)},this)});return this._publisherStash[a]}}b.prototype.afterChange=function(a){this.afterChangeSubscribers.push(a);return this};b.prototype.beforeChange=function(a){this.beforeChangeSubscribers.push(a);return this};b.prototype.onGet=function(a){this.onGetSubscribers.push(a);
return this};b.prototype.afterSet=function(a){this.afterSetSubscribers.push(a);return this};b.prototype.beforeSet=function(a){this.beforeSetSubscribers.push(a);return this};b.prototype.callSubscribers=function(){var a,b,d,c,e;d=arguments[0];b=2<=arguments.length?f.call(arguments,1):[];if(d!=null){c=0;for(e=d.length;c<e;c++)a=d[c],a.apply(null,b);return this}else return null};b.prototype.get=function(){this.callSubscribers(this.onGetSubscribers,this.value);return this.value};b.prototype.set=function(a){var b;
b=this.value;a===b?(this.callSubscribers(this.beforeSetSubscribers,b,a),this.value=a):(this.callSubscribers(this.beforeChangeSubscribers,b,a),this.callSubscribers(this.beforeSetSubscribers,b,a),this.value=a,this.callSubscribers(this.afterChangeSubscribers,b,a));return this.callSubscribers(this.afterSetSubscribers,b,a)};return b}();exports.getPublisher=function(b){return this._publisherStash[b]}}).call(this);
